services:
  ldu-agent:
    image: lazydockup-agent
    container_name: lazydockup-agent
    ports:
      - 5001:5001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/user/docker:/stacks
    environment:
      - HOST_PATH_BASE=/home/user/docker
      - DW_HOSTNAME=MyClientSystem
    restart: unless-stopped
