services:
  ldu-server:
    build: ./server
    container_name: lazydockup-server
    ports:
      - "5000:5000"
    environment:
      - AGENTS=ldu-agent:5001,192.168.0.44:5001
      - APP_LANG=de        # <--- HIER AUF DEUTSCH STELLEN
      - TZ=Europe/Berlin   # <--- ZEITZONE
      - KUMA_PUSH_URL="https://kuma.example.com/api/push/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx?status=up&msg=OK&ping="
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    restart: unless-stopped

  ldu-agent:
    build: ./agent
    container_name: lazydockup-agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/user/docker:/stacks
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      - HOST_PATH_BASE=/home/user/docker
      - DW_HOSTNAME=Docker-Host
      - TZ=Europe/Berlin
    restart: unless-stopped
